import type { IconType } from "react-icons";
import {
  IoArrowRedoOutline,
  IoArrowUndoOutline,
  IoCheckmarkCircleOutline,
  IoCopyOutline,
  IoPinOutline,
  IoTrashOutline,
  IoAdd,
  IoAddCircleOutline,
  IoArchiveOutline,
  IoArrowUp,
  IoBookmarkOutline,
  IoBuildOutline,
  IoCalendarOutline,
  IoCallOutline,
  IoCameraOutline,
  IoChatbubblesOutline,
  IoCheckmark,
  IoCheckmarkDone,
  IoChevronBack,
  IoChevronDown,
  IoChevronForward,
  IoChevronUp,
  IoClose,
  IoDownloadOutline,
  IoEyeOutline,
  IoCodeSlashOutline,
  IoConstructOutline,
  IoDocumentTextOutline,
  IoDesktopOutline,
  IoFolderOutline,
  IoGiftOutline,
  IoGlobeOutline,
  IoHappyOutline,
  IoKeypadOutline,
  IoLanguageOutline,
  IoLockClosedOutline,
  IoPhonePortraitOutline,
  IoServerOutline,
  IoVideocamOutline,
  IoEllipsisVertical,
  IoFileTrayFullOutline,
  IoInformationCircleOutline,
  IoLinkOutline,
  IoLogOutOutline,
  IoMegaphoneOutline,
  IoMenuOutline,
  IoMicOutline,
  IoMoonOutline,
  IoNotificationsOutline,
  IoPencil,
  IoPeopleOutline,
  IoPersonAddOutline,
  IoPersonOutline,
  IoQrCodeOutline,
  IoRemoveCircleOutline,
  IoSearchOutline,
  IoSettingsOutline,
  IoShieldCheckmarkOutline,
  IoStar,
  IoSunnyOutline,
  IoSyncCircleOutline,
  IoWalletOutline,
} from "react-icons/io5";
import { cn } from "@/lib/utils";

export interface IconProps {
  icon: IconType;
  size?: number;
  className?: string;
}

/** iOS uslubidagi Ionicons 5 wrapper */
export function Icon({ icon: Component, size = 24, className }: IconProps) {
  return (
    <Component
      size={size}
      className={cn("shrink-0", className)}
      aria-hidden
    />
  );
}

export {
  IoAdd as IconAdd,
  IoArrowRedoOutline as IconForward,
  IoArrowUndoOutline as IconReply,
  IoCheckmarkCircleOutline as IconSelect,
  IoCopyOutline as IconCopy,
  IoPinOutline as IconPin,
  IoTrashOutline as IconTrash,
  IoAddCircleOutline as IconZoomIn,
  IoArchiveOutline as IconArchive,
  IoArrowUp as IconArrowUp,
  IoBookmarkOutline as IconBookmark,
  IoBuildOutline as IconBuild,
  IoCallOutline as IconCall,
  IoCameraOutline as IconCamera,
  IoChatbubblesOutline as IconChat,
  IoCheckmark as IconCheck,
  IoCheckmarkCircleOutline as IconCheckCircle,
  IoCheckmarkDone as IconCheckDone,
  IoChevronBack as IconChevronBack,
  IoChevronDown as IconChevronDown,
  IoChevronForward as IconChevronForward,
  IoChevronUp as IconChevronUp,
  IoClose as IconClose,
  IoDownloadOutline as IconDownload,
  IoEyeOutline as IconEye,
  IoCalendarOutline as IconCalendar,
  IoCodeSlashOutline as IconCode,
  IoConstructOutline as IconConstruct,
  IoDesktopOutline as IconDesktop,
  IoDocumentTextOutline as IconDocument,
  IoFolderOutline as IconFolder,
  IoGiftOutline as IconGift,
  IoGlobeOutline as IconGlobe,
  IoHappyOutline as IconEmoji,
  IoKeypadOutline as IconKeyboard,
  IoLanguageOutline as IconLanguage,
  IoLockClosedOutline as IconLock,
  IoPhonePortraitOutline as IconDevices,
  IoServerOutline as IconStorage,
  IoVideocamOutline as IconVideo,
  IoInformationCircleOutline as IconInfo,
  IoLinkOutline as IconLink,
  IoLogOutOutline as IconLogOut,
  IoEllipsisVertical as IconMore,
  IoFileTrayFullOutline as IconInbox,
  IoMegaphoneOutline as IconMegaphone,
  IoMenuOutline as IconMenu,
  IoMicOutline as IconMic,
  IoMoonOutline as IconMoon,
  IoNotificationsOutline as IconNotifications,
  IoPencil as IconPencil,
  IoPeopleOutline as IconPeople,
  IoPersonAddOutline as IconPersonAdd,
  IoPersonOutline as IconPerson,
  IoQrCodeOutline as IconQrCode,
  IoRemoveCircleOutline as IconZoomOut,
  IoSearchOutline as IconSearch,
  IoSettingsOutline as IconSettings,
  IoShieldCheckmarkOutline as IconShield,
  IoStar as IconStar,
  IoSunnyOutline as IconSun,
  IoSyncCircleOutline as IconStories,
  IoWalletOutline as IconWallet,
};
